import type { ListResource } from '@arpadroid/resources';
import type ListItem from '../listItem/listItem.js';
import type { ListItemConfigType } from '../listItem/listItem.types';
import type { ArpaElementConfigType } from '@arpadroid/ui';
import type { ListResourceItemType, Router } from './list.js';
import { FieldOptionConfigType } from '@arpadroid/forms';
import { NavLinkConfigType } from '@arpadroid/navigation';

export type ListConfigType = ArpaElementConfigType & {
    allControls?: boolean;
    actions?: FieldOptionConfigType[];
    canCollapse?: boolean;
    controls?: string[];
    defaultView?: string;
    paramNamespace?: string;
    hasControls?: boolean;
    hasInfo?: boolean;
    hasItemsTransition?: boolean;
    hasMiniSearch?: boolean;
    hasPager?: boolean;
    hasResource?: boolean;
    hasSearch?: boolean;
    hasSelection?: boolean;
    hasStickyFilters?: boolean;
    heading?: string;
    id?: string;
    isCollapsed?: boolean;
    itemComponent?: typeof ListItem;
    items?: ListItemConfigType[];
    itemsPerPage?: number;
    itemTag?: string;
    listResource?: ListResource;
    listSelector?: string;
    noItemsContent?: string;
    noItemsIcon?: string;
    onSearch?: (value: string) => void;
    pageParam?: string;
    perPageParam?: string;
    preProcessItem?: (item: ListConfigType) => ListConfigType;
    preProcessNode?: (node?: ListItem | HTMLElement) => ListItem | HTMLElement;
    renderMode?: 'minimal' | 'full';
    resetScrollOnLoad?: boolean;
    searchParam?: string;
    showResultsText?: boolean;
    sortByParam?: string;
    sortDefault?: string;
    sortDirParam?: string;
    sortOptions?: FieldOptionConfigType[];
    stickyControls?: boolean;
    router?: Router;
    template?: string;
    title?: string | null;
    viewOptions?: NavLinkConfigType[];
    views?: string[];
    zoneSelector?: string;
    mapItemId?: (item: ListResourceItemType) => string;
};
