import type { ListResource } from '@arpadroid/resources';
import type ListItem from '../listItem/listItem.js';
import type { ListItemConfigType, ListItemImageTypes } from '../listItem/listItem.types';
import type { ArpaElementConfigType } from '@arpadroid/ui';
import type { ListResourceItemType, Router } from './list.js';
import { BaseLinkConfigType, BaseFieldOptionConfigType } from '../../@types/base.types.js';

export type ListConfigType = ArpaElementConfigType & {
    actions?: BaseFieldOptionConfigType[];
    canCollapse?: boolean;
    controls?: string[];
    defaultView?: string;
    hasControls?: boolean;
    hasInfo?: boolean;
    hasItemsTransition?: boolean;
    hasMiniSearch?: boolean;
    hasPager?: boolean;
    hasMessages?: boolean;
    hasPreloader?: boolean;
    hasResource?: boolean;
    heading?: string;
    imageSize?: ListItemImageTypes;
    id?: string;
    itemIdMap?: string;
    isCollapsed?: boolean;
    itemComponent?: typeof ListItem;
    items?: ListItemConfigType[];
    lazyLoadImages?: boolean | 'auto';
    itemsPerPage?: number;
    itemTag?: string;
    tagName?: string;
    listResource?: ListResource;
    listSelector?: string;
    maxPagerNodes?: number | string;
    mapItemId?: (item: ListResourceItemType) => string;
    noItemsContent?: string;
    noItemsIcon?: string;
    onSearch?: (value: string) => void;
    pageParam?: string;
    paramNamespace?: string;
    perPageParam?: string;
    preProcessItem?: (item: ListConfigType) => ListConfigType;
    preProcessNode?: (node?: ListItem | HTMLElement | undefined) => ListItem | HTMLElement | undefined;
    renderMode?: 'minimal' | 'full';
    resetScrollOnLoad?: boolean;
    router?: Router;
    searchParam?: string;
    showResultsText?: boolean;
    sortByParam?: string;
    sortDefault?: string;
    sortDirParam?: string;
    sortOptions?: BaseFieldOptionConfigType[];
    stickyControls?: boolean;
    template?: string;
    title?: string | null;
    titleIcon?: string;
    viewOptions?: BaseLinkConfigType[];
    views?: string[];
};
