import { ListResource } from '@arpadroid/resources';
import { ListItemInterface } from '../../types.compiled';
import ListItem from '../listItem/listItem.js';

export interface ListInterface {
    allControls?: boolean;
    canCollapse?: boolean;
    defaultView?: string;
    paramNamespace?: string;
    hasControls?: boolean;
    hasInfo?: boolean;
    hasMiniSearch?: boolean;
    hasPager?: boolean;
    hasResource?: boolean;
    hasSearch?: boolean;
    hasSelection?: boolean;
    hasStickyFilters?: boolean;
    heading?: string;
    id?: string;
    isCollapsed?: boolean;
    itemComponent?: typeof ListItem;
    items?: ListItemInterface[];
    itemsPerPage?: number;
    itemTag?: string;
    listResource?: ListResource;
    noItemsContent?: string;
    noItemsIcon?: string;
    onSearch?: (value: string) => void;
    pageParam?: string;
    perPageParam?: string;
    preProcessItem?: (item: ListInterface) => void;
    preProcessNode?: (node: HTMLElement) => void;
    renderMode?: 'minimal' | 'full';
    resetScrollOnLoad?: boolean;
    searchParam?: string;
    showResultsText?: boolean;
    sortByParam?: string;
    sortDefault?: string;
    sortDirParam?: string;
    sortOptions?: any[];
    stickyControls?: boolean;
    template?: string;
    title?: string;
    viewOptions?: NavLinkInterface[];
    views?: string[];
}
